CREATE DATABASE BOOK_STORE;
USE BOOK_STORE;
CREATE TABLE BOOKS(
BOOK_ID INT PRIMARY KEY auto_increment,
TITLE VARCHAR(40),
AUTHOR VARCHAR(25),
PRICE INT);

INSERT INTO BOOKS(TITLE,AUTHOR,PRICE)
VALUES
("HARRY POTTER","SHIVAJI",1399),
("LEGACY OF SPIDERMAN","STAN LEE",1899),
("CHAOUS WALKING","TESMAN",1499),
("LORD OF RINGS","TOLKIE",799);

SELECT * FROM BOOKS;

SELECT TITLE,PRICE FROM BOOKS;
SELECT * FROM BOOKS WHERE PRICE >1000;

UPDATE BOOKS
SET AUTHOR = "UNKNOWN"
WHERE BOOK > 0;

UPDATE BOOKS
SET PRICE = 2000
WHERE BOOK_ID = 4;

DELETE FROM BOOKS
WHERE BOOK_ID= 4;

SELECT * FROM BOOKS;